// ⚠️ FICHIER AUTO-GÉNÉRÉ — ne pas modifier manuellement
// Modifie CLIENT.md puis relance : npm run sync-client

export const clientConfig = {
  identity: {
    prenomDirigeant: "Brendan",
    nomDirigeant: "Trehin",
    nomEntreprise: "TRH Plomberie Carrelage",
    nomLegal: "TRH PLOMBERIE CARRELAGE",
    genreDirigeant: "masculin",
    founder: "Brendan Trehin",
  },
  contact: {
    telephone: "06 58 18 88 15",
    telephoneHref: "tel:+33658188815",
    telephoneUrgence: "06 58 18 88 15",
    email: "contact@trh-plomberie-carrelage.fr",
    adresse: "76 Route de Larmor, 12 La Vraie Croix",
    ville: "Ploemeur",
    codePostal: "56270",
    departement: "Morbihan",
    region: "Bretagne",
    zoneIntervention: "Ploemeur et 30km autour",
    zoneKm: "30",
  },
  horaires: {
    semaine: "7h30 – 19h00",
    samedi: "8h00 – 17h00",
    dimanche: "Fermé (sauf urgence)",
    urgence: "7j/7 — 7h00 – 21h00",
  },
  branding: {
    couleurPrimaireHue: "210",
    couleurAccentHue: "30",
  },
  social: {
    facebook: "",
    instagram: "",
    google: "",
  },
  domaine: "trh-plomberie-carrelage.fr",
  url: "https://www.trh-plomberie-carrelage.fr",
  legal: {
    siret: "993 051 879",
    rge: "",
    assuranceDecennale: "Assuré — attestation sur demande",
  },
  chiffres: {
    anneesExperience: 10,
    nombreInterventions: 500,
    noteGoogle: 5,
    nombreAvis: 3,
    anneeCreation: 2025,
    delaiIntervention: "2h",
    disponibilite: "7j/7",
    tauxSatisfaction: "100",
  },
  geo: {
    latitude: "47.7333",
    longitude: "-3.4333",
  },
  communes: [
    { name: "Ploemeur", postalCode: "56270" },
    { name: "Lorient", postalCode: "56100" },
    { name: "Larmor-Plage", postalCode: "56260" },
    { name: "Guidel", postalCode: "56520" },
    { name: "Quéven", postalCode: "56530" },
    { name: "Lanester", postalCode: "56600" },
    { name: "Hennebont", postalCode: "56700" },
    { name: "Gestel", postalCode: "56530" },
    { name: "Pont-Scorff", postalCode: "56620" },
    { name: "Riantec", postalCode: "56670" },
    { name: "Caudan", postalCode: "56850" },
    { name: "Cléguer", postalCode: "56620" },
    { name: "Inzinzac-Lochrist", postalCode: "56650" },
    { name: "Brandérion", postalCode: "56700" },
    { name: "Kervignac", postalCode: "56700" },
  ],
  services: [
    { title: "Dépannage urgent", shortDescription: "Intervention rapide pour toutes vos urgences plomberie dans le pays de Lorient.", description: "Fuite d'eau, canalisation bouchée, dégât des eaux, panne de chauffe-eau... Brendan intervient en urgence 7j/7 dans un rayon de 30 km autour de Ploemeur. Diagnostic sur place et réparation immédiate dans la majorité des cas.", icon: "Siren", slug: "/depannage-plomberie" },
    { title: "Plomberie générale", shortDescription: "Installation, remplacement et mise aux normes de vos équipements sanitaires.", description: "Robinetterie, tuyauterie, raccordements, WC, éviers, recherche de fuite... J'interviens pour tous vos travaux de plomberie, de l'installation neuve à la mise aux normes de vos installations existantes.", icon: "Wrench", slug: "/plomberie" },
    { title: "Salle de bain", shortDescription: "Rénovation complète avec plomberie et carrelage, douche italienne, adaptation PMR.", description: "De la conception à la réalisation, je prends en charge votre projet de rénovation de salle de bain. Plomberie et carrelage intégrés : douche italienne, remplacement baignoire, accessibilité PMR, meuble vasque... Un seul interlocuteur du début à la fin.", icon: "Bath", slug: "/renovation-salle-de-bain" },
    { title: "Carrelage", shortDescription: "Pose de carrelage et faïence pour sols et murs, intérieur et extérieur.", description: "Pose de carrelage, faïence, mosaïque et grès cérame pour tous vos projets : salle de bain, cuisine, séjour, terrasse. Préparation des supports, ragréage, étanchéité et pose soignée. Tous formats et tous styles.", icon: "Grid3x3", slug: "/carrelage" },
    { title: "Chauffage", shortDescription: "Installation et dépannage de chaudière, pompe à chaleur, plancher chauffant.", description: "Installation et remplacement de chaudière gaz condensation, pompe à chaleur air-eau, plancher chauffant, radiateurs. Entretien annuel obligatoire et dépannage de votre système de chauffage.", icon: "Flame", slug: "/chauffage" },
    { title: "Chauffe-eau", shortDescription: "Remplacement, ballon thermodynamique, détartrage et entretien.", description: "Remplacement de chauffe-eau électrique ou gaz, installation de ballon thermodynamique pour réduire votre facture énergétique. Détartrage et entretien pour prolonger la durée de vie de votre équipement.", icon: "Droplets", slug: "/chauffe-eau" },
  ],
  testimonials: [
    { name: "Sophie L.", rating: 5, text: "Brendan est intervenu rapidement pour une fuite dans notre salle de bain à Ploemeur. Travail propre et soigné, tarif très correct. Je recommande sans hésiter !", date: "2026-01-15", source: "Google" },
    { name: "Jean-Marc D.", rating: 5, text: "Rénovation complète de notre salle de bain : plomberie et carrelage impeccables. Brendan est ponctuel, sérieux et de bon conseil. Résultat au-delà de nos attentes.", date: "2026-02-03", source: "Google" },
    { name: "Marie-Anne K.", rating: 5, text: "Intervention en urgence un samedi matin pour un WC bouché à Lorient. Brendan est arrivé en moins d'une heure. Problème résolu en un rien de temps. Merci !", date: "2025-12-20", source: "Google" },
    { name: "Patrick M.", rating: 5, text: "Pose de carrelage dans notre cuisine à Guidel. Le travail est remarquable, les joints sont parfaits. Un vrai artisan qui prend soin de son travail.", date: "2026-01-28", source: "Google" },
    { name: "Nathalie R.", rating: 5, text: "Remplacement de notre vieux chauffe-eau par un modèle thermodynamique à Larmor-Plage. Installation propre et explications claires sur le fonctionnement. Très professionnel.", date: "2026-02-10", source: "Google" },
    { name: "Yann B.", rating: 4, text: "Bon travail pour le raccordement de notre machine à laver et la pose de faïence derrière l'évier. Petit délai d'attente pour le rendez-vous mais travail de qualité.", date: "2026-01-08", source: "Google" },
    { name: "Isabelle G.", rating: 5, text: "Brendan a refait entièrement la douche italienne de notre maison à Quéven. Carrelage grand format, niche intégrée, tout est parfait. Artisan sérieux et minutieux.", date: "2025-12-05", source: "Google" },
    { name: "Christophe F.", rating: 5, text: "Dépannage rapide et efficace pour une fuite sous l'évier à Lanester. Prix très raisonnable et travail bien fait. Je n'hésiterai pas à refaire appel à lui.", date: "2026-02-18", source: "Google" },
    { name: "Françoise P.", rating: 5, text: "Pose de carrelage dans notre salle de bain et notre entrée à Hennebont. Brendan est à l'écoute, les finitions sont soignées. Un artisan de confiance.", date: "2026-01-22", source: "Google" },
    { name: "Didier C.", rating: 5, text: "Réfection complète de la plomberie dans notre maison ancienne à Gestel. Brendan a su s'adapter aux contraintes du bâti ancien. Travail sérieux et propre.", date: "2025-11-28", source: "Google" },
  ],
  admin: {
    password: "1234",
  },
  seo: {
    metaTitleAccueil: "Plombier Carreleur Ploemeur — TRH Plomberie Carrelage | Dépannage 7j/7",
    metaDescAccueil: "Plombier carreleur à Ploemeur et Lorient. Dépannage urgent 7j/7, installation sanitaire, rénovation salle de bain, pose carrelage. Devis gratuit.",
    descriptionEntreprise: "Plombier carreleur à Ploemeur (56). Dépannage urgent 7j/7, installation sanitaire, rénovation salle de bain, pose de carrelage et faïence. Devis gratuit — Brendan Trehin.",
    slogan: "Votre plombier carreleur à Ploemeur — Dépannage 7j/7, intervention rapide",
  },
} as const;

export type ClientConfig = typeof clientConfig;
